# https://danielsaidi.com/blog/2022/05/11/schedule-github-pages-rebuild-with-github-actions

name: autobuild

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url  https://api.github.com/repos/yassine-hamoudi/labri/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: $
