name: Deploy Webdav

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jinjat-data/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.USER_TOKEN }}
          source-directory: public
      - uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.WEBDAV_ADDRESS }}
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/
          include: 'public/**'
