name: Deploy Webdav

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.WEBDAV_ADDRESS }}
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/
          include: '_site/**'
