name: Upload WebDAV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger GitHub pages rebuild
        run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $USER_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/yassine-hamoudi/labri/pages/builds
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
      - uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.WEBDAV_ADDRESS }}
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/
          include: '_site/**'
