name: Deploy Webdav

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
    - gh-pages

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.3.0'
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: Webdav deploy
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.WEBDAV_ADDRESS }}
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/
          include: '_site/**'
