name: Upload WebDAV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: "https://webdav.labri.fr/vhosts/quantique.labri.fr"
          webdav_username: ${{secrets.WEBDAV_USERNAME}}
          webdav_password: ${{secrets.WEBDAV_PASSWORD}}
          webdav_upload_path: "/vhosts/quantique.labri.fr/"
          files: "README.md"
          keep_structure: true
