name: Upload WebDAV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.WEBDAV_ADDRESS}}
          webdav_username: ${{secrets.WEBDAV_USERNAME}}
          webdav_password: ${{secrets.WEBDAV_PASSWORD}}
          webdav_upload_path: "/"
          files: "_site/**"
          keep_structure: true
